title: SiyahSensei's Homepage

background: https://github.com/siyahsensei/gethomepage-configs/blob/main/blossom_valley.jpg

theme: dark

blockHighlights:
  levels:
    good: "bg-emerald-500/40 text-emerald-950 dark:bg-emerald-900/60 dark:text-emerald-400"
    warn: "bg-amber-300/30 text-amber-900 dark:bg-amber-900/30 dark:text-amber-200"
    danger: "bg-rose-700/45 text-rose-200 dark:bg-rose-950/70 dark:text-rose-400"

headerStyle: clean

base: https://homepage.local.siyahsensei.com/

language: en

target: _blank

providers:
  openweathermap: xxxxx

instanceName: public
